#!/bin/sh

username='jenkinsci'
if [ -z "$1" ]; then
  echo "Using jenkinsci/* for clones";
else
  echo "Using '$1' for clones";
  username=$1
fi

for p in $(cat demo/plugins.txt | grep -E 'workflow-|pipeline-' | grep -v 'pipeline-rest-api' | grep -v 'workflow-aggregator'); do
  echo "$p"
  git clone git@github.com:$username/$p-plugin.git ../$p-plugin
done
